### PR TITLE
Add support for PKCS#8 files to OpenSSL wrapper

### PR DESCRIPTION
**Pull request by tomato42**
OpenSSL can output files either in SSLay PEM or PKCS#8 PEM format depending on the way it is called. Make the OpenSSL wrapper support both of them.

### CODE REVIEW

**Comment by trevp** [comment]
Could you expand the comments?  Right now it's not clear exactly what this case is for, and I'm not really sure what you mean by "it" or "the library" (are you talking about tlslite or openssl)?

**Comment by tomato42** [comment]
by "it" I meant OpenSSL CLI utility

OpenSSL when used to generate a self signed certificate in one step, for example like this:
`openssl req -x509 -newkey rsa:1024 -keyout localhost.key -out localhost.crt -subj /CN=localhost -nodes -batch -sha256` will generate a file (PKCS#8) with a "-----BEGIN PRIVATE KEY-----" header that is in different format than what `openssl genrsa -out key.pem 1024` will generate, indicated by "-----BEGIN RSA PRIVATE KEY-----" header (so called SSLay format)

and what is most important the PKCS#8 format files can't be read by `m2.rsa_read_key()`

**Comment by trevp** [comment]
Sorry, I meant add to the comments in the code.

**Comment by tomato42** [comment]
aah, then by "it" I meant the very code below

does that look good now?

**Pull request merged**
