### PR TITLE
[v4] Small TLSRecordLayer refactor

### PR DESCRIPTION
**Pull request by tomato42**
Prepare `TLSRecordLayer` for moving encryption and decryption to external class.

unit test coverage for sending and receiving records through socket, minimal test coverage for TLSRecordLayer (using private methods).

Changes since v1:
- fixup test cases for 2.6 and 3.4 compatibility

### CODE REVIEW

**Comment by trevp** [comment]
I haven't looked at this yet, but can you give some rationale  - where is this heading, why is it needed?

**Comment by tomato42** [comment]
The end goal is to put record layer encryption, decryption under unit tests.

The next pull request will extract encryption and decryption to separate object (something like 471b0c5 from pull #79 did, but cleaner), that will allow in turn to put EtM code under unit tests. I should have it ready tomorrow.

**Comment by trevp** [comment]
Hi Hubert, I still don't understand the purpose of moving all this code around.  Why can't you unit-test the functions as is?

You trying to re-organize a lot of complex code.  That adds significant risk that bugs might creep in.  I'd have to spend a lot of time validating that everything is the same.  And I still might make a mistake!

If this added major new features to the library, that would be one thing.  But I don't see that you're adding anything essential, you're just trying to make the code cleaner (from your perspective).

I think you either need to give me a better understanding why these changes are important, or drop them and focus on smaller and more surgical pull requests that are easy to verify and that add clear improvements.

**Comment by tomato42** [comment]
in no particular order, speaking of whole EtM patchset:

 * test cases for refactored code are much simpler
 * using private methods in unittests is bad form
 * I also want to later add support for handling fragmented messages - that too will be cleaner with record layer in separate class
 *  for the `tlsfuzzer` I need access to sending raw messages - I don't want to depend on private methods for that
 * TLSRecordLayer is a big class that does both handshaking and handling record layer - adding EtM only makes it larger
 * methods for sending and receiving messages are similarly problematic - very long and complex, do multiple things

Doing small surgical pull requests will simply increase the technical debt, making the code less readable.

**Comment by trevp** [comment]
So you want some private methods to be public?  That's a lot easier / less risky than refactoring and rewriting a bunch of code.

Regarding making test cases "simpler" - I'm not convinced that's a good reason to rewrite complex security-critical code that is working.

I also don't understand why your refactor / rewrite is that much better.  The division of labor between TLSRecordLayer, RecordLayer, and RecordSocket is not clear to me, the names are confusing, and there's some new error handling (new exceptions) also being added, which I'm not sure why is part of a refactor.

Small pull requests that add single specific improvements to the code are MUCH easier to validate.  Maybe you need to move towards your goal in smaller steps where I can clearly understand what benefit each small change is making.  Or focus on just making a few small changes.

But right now this seems like a lot of code movement for little benefit.

**Comment by tomato42** [comment]
I want to be able to handle what (and if at all) the alerts are sent. That's impossible to change without big refactor anyhow.

extraction of code from TLSRecordLayer is not done yet, so it's understandable that it is a bit unclear. RecordSocket is handling sending and receiving TLS records over network sockets, RecordLayer implements the crypto needed to make records work, later it will also do the message fragmentation (though mostly by just using a helper class). TLSRecordLayer will handle the message parsing.

I was initially working to make TLSRecordLayer do actually just the record layer stuff but that resulted in far more code movement.

The patches as they already are simple, it may be possible to make them simpler but not by much. Should I break additions of every method and every test case to a single patch? Without you pointing me which are too complex and what makes them too complex I won't be able to change them to suit you.

**Comment by trevp** [comment]
Your comment about alerts is new to me, I also didn't know that "extraction of code from TLSRecordLayer is not done yet".

From my perspective, this is a lot of work to clean up code that is clean enough.  I have very little time to spend on this, and there's a lot of easy room for improvement by adding features, so I'd rather spend my time accepting those changes, not complex refactoring.

Because this is a security library, and has users, security and stability are primary concerns.  Moving code around has a risk of bugs.  So I don't want to do it unless there's very good reasons and the changes are extremely simple and clear.

You're trying to build a testing tool, so your priorities are different - maybe it makes sense to re-engineer the library so that you can program every aspect and do weird stuff.  But it's possible you just need to make a fork for that.

Anyways, think on whether you can live without these changes, or if there's surgical changes that would suffice.  Otherwise, it's possible our goals are just incompatible.

**Comment by tomato42** [comment]
about alerts: if there are errors encountered during decryption, the _getNextRecord will send alert automatically

Sorry, but I can't agree that multiple 100-line methods is "clean code". Methods which *need* to be broken up to implement EtM or AEAD for that matter... it's not possible to make those changes "extremely simple and clear", the previous version required for that "just" patches changing 260 lines: https://github.com/tomato42/tlslite-1/commit/471b0c599a9fbac0ab9701816062cccf1b19c846

Yes, I have a bit different goal, but I don't think what accounts to 1% change in *how* the code works (not change in overall behaviour) is worth a fork. But if you don't think that support for fragmented messages, Encrypt-then-MAC and ECDHE (just listing from code I already have) is worth your time reviewing changes that clean up code and add unit test coverage, then yes, we definitely have different priorities. And for the tester what I need is just record layer, crypto and message serialisation and deserialisation. I certainly won't touch any of the handshaking logic in TLSConnection or TLSRecordLayer. Or in other words, the changes in this pull requests are everything I need, other stuff (`extensions` in client and server hello) you already merged.

I will try to expose the methods inside TLSRecordLayer, but it will be ugly and it certainly won't be simple and clear, but I'll let you be the judge

**Comment by trevp** [comment]
> Sorry, but I can't agree that multiple 100-line methods is "clean code".

I hope you never have to read OpenSSL source! :-)

Anyways, I'll accept new features if the patches are easy to review and make minimal changes, I just don't have time to do larger refactoring.

**Comment by tomato42** [comment]
OpenSSL is also a library that has most often and most severe security vulnerabilities. I see a correlation here... :)

I think we can aim higher.

**Comment by tomato42** [comment]
> I will try to expose the methods inside TLSRecordLayer, but it will be ugly and it
> certainly won't be simple and clear, but I'll let you be the judge

the code is in pull #99, a "simple" 350 lines patch after squashing...

**Pull request closed without merging**
