### PR TITLE
[test merge] fix all problems with tests

### PR DESCRIPTION
**Pull request by tomato42**
(this is a squashed merge of pull #71 and #72 )

update the expired certificate

The previous certificate had very short validity period, create a
new one that has 10 year lifetime

use FIFO for integration tests synchronisation

because Travis-CI servers are sometimes under heavy load, the
synchronisation using `time.sleep(2)` is not deterministic,
change it to use Unix FIFO

Server writes a single character (that's non-blocking) to FIFO
when it has set up and is able to handle requests from client.
The client tries to read a single character (that's blocking)
before trying to connect to server.

### CODE REVIEW

**Comment by trevp** [comment]
os.mkfifo() won't work on Windows, is there a fix that preserves Windows compatibility?

**Comment by tomato42** [comment]
we could use just regular network socket instead... the important part is the block-on-read

**Comment by trevp** [comment]
hm, then we need 2 ports, sort of annoying.  But another limitation with the fifo is it constrains the tests to running on the same machine.  

Not sure what the best answer is.  Maybe 2 ports is OK?  Maybe fifo if it's available (both client on server on UNIX, and same machine), but just fall back to previous behavior if not?

But I think we should preserve the ability to run tests on Windows, and between different machines.

**Comment by tomato42** [comment]
well, we already do use 2 ports - HTTP and XMLRPC run on separate port so it will be the 3rd one :)

so I'd say it's not a complete blocker, I'll rework it.

**Comment by tomato42** [comment]
ok, pull requests ready:
 - #72 fixes the bad certificate
 - #75 fixes the random failures (updated to use sockets)
 - #76 introduces tackpy to tests (but depends on #72)

**Comment by tomato42** [comment]
obsoleted by #77

**Pull request closed without merging**
