### PR TITLE
[RFC] Support for fragmented handshake messages

### PR DESCRIPTION
**Pull request by tomato42**
Make the implementation actually compatible with RFC 5246 Section 6.2.1 - in other words, fragment handshake messages and handle fragmented handshake messages.

Just a Request For Comment (see my comments for specific questions), I still want to refactor the function to make it less "beastly"

### CODE REVIEW

**Comment by trevp** [comment]
Hmm, it seems weird that applayer fragmentation is handled in writeAsync, and handshake fragmentation in sendMsg.

Also, if you could split out any of the smaller pieces of this, I'd definitely rather handle small/easy pull requests one at a time.

**Comment by tomato42** [comment]
> Hmm, it seems weird that applayer fragmentation is handled in writeAsync, and handshake
> fragmentation in sendMsg.

yeah, I don't like that either, but problem is that writeAsync is public while _sendMsg is used by TLSConnection. To make it all clean will require implementing the separate content types as separate streams - and for that I'll need to rework significant portion of tlsconnection and tlsrecordlayer (which will probably cause an API change). I'd rather postpone that for now.

> Also, if you could split out any of the smaller pieces of this, I'd definitely rather handle small/easy
> pull requests one at a time.

I'm afraid this is the smallest possible patch to implement that - it looks big because it changes indentation level of the whole method, the actual code changes are small. I have reworked the method a bit more to make it more readable, take a look at: https://github.com/tomato42/tlslite-1/blob/my-master-2/tlslite/tlsrecordlayer.py#L931 (not finished, I have small problem with test cases in the intermediate commits) it should make the changes a bit more obvious. I may try to fist extract the duplicate code to methods and then rework it - that should cause the patches to be smaller but there will be more of them (this will require more work, so I'd rather not do it, please see if you would be happy with the resulting code being readable)

**Comment by trevp** [comment]
But writeAsync calls sendMsg, so why wouldn't the fragmentation for everything be in sendMsg?  I won't have time to look at this seriously until next week, but having the fragmentation logic in two places feels wrong.

You may be right that this change can't be sliced into smaller pieces, but in general I'd much rather work through small, incremental pull requests where possible.

**Comment by tomato42** [comment]
ok, will try to rework it to fix this

**Comment by tomato42** [comment]
reworked pull request ready: pull #41

**Pull request closed without merging**
